name:          ShopPad Code Guide
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://shoppad.github.io/code-guide/

markdown:      rdiscount
permalink:     pretty
pygments:      true
